travis:
  secure:
    BINSTAR_TOKEN: GYWMsbExY8lIXg6nR0qMYUYYOVfMuSMRfjJ5O0mtcZZ8IEmYKTr+M6OnUVemEg5aSbsS7TUwvQu4pjpY+SoY57fGAEYMqgxJ6Oe9yY0Fo764dCXvLvZHnCztSdjrP8RdwIuLCSXbbQWBC3ZvUjDZprXHQbhdg7xhemQBJZxVTwr19yXAjvhAOBoJ2ytbnJqqu8xBIWCJsnIUYtbuQlwn7B5GAU+ZkE6QDguak4xQgxGUpithw2/denkUOwJGUNylZ+aXn3HFRUs69Zwzx9CFe60B72/Q7kGe+YDyqr3BaZuqbLnjcIzXvwRypVWpD2tfmASIfz2QClUG7omNn7lRCzxWsaERHwgdakGgiOP4twbOAQvr7R94EGBQdrfB2vb7diShpUMNVzeq82508AmHxnBxCpwErVXZIn8OtGr++7GlTq6StDRgL44KNRVFpGniHjBvUOEDhpWd/1WRoyK5AyNxRuKNLQpifCei8u1muSXLX57TjssXiwxXcQ9nQApCVbWHOYfW2sOJj6Ei53vqSzov4dTbUzftbJK7O2nGegXhwAc1vBc9ex9jBTTsHZ2l7rMpFn6uckzX7bZEGxb4+mnqrCOL8Ek1OKhBA5hA9UJ5Lk3hjuGrVu7Va81AIycuNNisWamundS5CFMBb8h9UlNn9/9E8fqSVio/S8PCAnU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
